### ISSUE TITLE
Big Data Research Paper

### ISSUE THREAD

**Issue by VidyaSamadi** [VidyaSamadi/Research-Team#3]
Writing a research paper on Big Data

**Comment by VidyaSamadi** [comment]
Ellie: As you move forward with writing the literature review portion. Ryne (Water Resources PhD student) will help you and supervise you along. Thank you.

**Comment by echao110** [comment]
@VidyaSamadi Yes ma'am. 

@rynep Hi Ryne. My name is Ellie Chao, nice to meet you. DOP and Dr. Samadi have talked highly of you and I am super excited and honored to have you supervising me. Just to let you know where I am - I am currently still reading the literature, I am just finishing up the second one. I am hoping by this Friday to have at least 2 article summary writing completed. I will send that to you to proofread when it is completed. Thanks in advance.

**Comment by rynep** [comment]
@echao110 Good to meet you Ellie, I look forward to working with you as well. Just send me the summary and articles you are referencing once you are ready for a review.

**Comment by rynep** [comment]
@echao110 Ellie I just wanted to check in and see how things are going?

**Comment by echao110** [comment]
@rynep Hey Ryne sorry for not following up. I caught a fever last week so I wasn’t able to finish the summary last Friday like I wanted. I’ve been doing some catching up this week to make up for that lost time. There are a total of 6 articles and I am currently on the 5th one. I’m planning on having them all read and summarized by tonight. When I complete it, I will send it to you for a review.

**Comment by echao110** [comment]
@rynep can you provide a suitable email that I can send the summary to you at?

**Comment by rynep** [comment]
@echao110 ryne@email.sc.edu

**Comment by VidyaSamadi** [comment]
Elli, have you finish the literature review part? Thank you

**Comment by echao110** [comment]
@vidyasamadi yes ma’am I have. I forgot to email it. I will email it as soon as I am home. Sorry!

**Comment by VidyaSamadi** [comment]
OK, Ellie. please cc me when you email it to Ryne.

**Comment by VidyaSamadi** [comment]
Ellie, please finalize the literature review and send it to Ryne TODAY. Thank you

**Comment by echao110** [comment]
@VidyaSamadi Yes ma'am, I have just sent it out.
@rynep I have just emailed the literature review out to you and cc Dr. Samadi in it. 

Thanks

**Comment by VidyaSamadi** [comment]
Ryne; thank you. Yes, it is gong to be a technical paper on software development that we are currently focusing. I’ll try to squeeze you into the co-authors team. 

Also, can you please send Ellie tide, flood, rainfall stations at the lower PeeDee region so that she can extract the datasets for Florence compound floods study. USGS02135000 at the little pee dee river could be one of the potential flood station. Look into both NCDC and NOAA-NOMADS data. Comments and discuss via GitHub,  please. Iam going to create a new issue for Florence compound flood project and will assign both of you on this task.

**Comment by rynep** [comment]
I'll look over stations this weekend and see which ones will be worth analyzing.

@echao110 please look into "rnoaa" package and "USGS-R" for quick acquisition of rainfall, tide, and discharge data.

**Comment by rynep** [comment]
@echao110 do you know how to use GIS?

**Comment by echao110** [comment]
@rynep I know a little bit. I took the GIS class with Dr. Samadi.

**Comment by VidyaSamadi** [comment]
@echao110 please finish up the literature review and send it to @pleuk515667 . Have you downloaded rainfall and flood data from NOAA and USGS websites?

@rynep Please help Ellie to organize compound flood datasets (tide, floods, rain) with the same starting and ending date/time. She should collect Florence driven compound floods data from Sep. 13 until Oct. 13, 2018. 

Thank you all.

**Comment by rynep** [comment]
@echao110 here is a link to USGS data and NCDC data. You can view sites on the map and export to GIS. NCDC you will have to map a selection, export to csv, and import as xy table to GIS. I like to get stations into GIS so I can check their proximity to each other. Also, check USGS 15-minute precipitation. There may be a discharge gauge that also collects precipitation data.

https://waterdata.usgs.gov/sc/nwis/current/?type=flow

https://gis.ncdc.noaa.gov/maps/ncei/cdo/hourly

**Comment by echao110** [comment]
@rynep thank you very much. 

@VidyaSamadi I am still getting the data because it would not let me download the file as one due to the limited spacing; so I have half of the data. I will get that done by Wednesday. I will have the literature review done later tonight and have that emailed to PK, I will cc you in the email.

**Comment by VidyaSamadi** [comment]
@echao110 OK, please work on data collection on Wed. and let me and Ryne know if you have any question. Thank you.

**Comment by rynep** [comment]
@echao110 how is the data gathering process going? Were you able to use the codes I sent? Please let me know if you have questions or need help with the codes.

**Comment by VidyaSamadi** [comment]
@echao110 please make the datasets ready by this Wednesday. We will meet at 2:30 pm. Let us know if you have any question. Thank you.
@rynep Thank you, Ryne.

**Comment by echao110** [comment]
@rynep sorry for just seeing this. I have been sick and forgot to reply back. Yes, the NOAA code is working very well. Thank you

@VidyaSamadi Dr. Samadi, I will be in class at that time. If you want 2:30, I can only do Friday at 2:30pm.

**Comment by VidyaSamadi** [comment]
@echao110  okay lets meet at 1 pm on Wed.

**Comment by echao110** [comment]
@VidyaSamadi Dr. Samadi, I am in class at that time. Senior Design goes from noon to 2pm. And then right after Senior Design, I have another class.

**Comment by echao110** [comment]
@VidyaSamadi

**Comment by echao110** [comment]
@rynep Happy Easter Ryne. Sorry to bother you on a weekend, but I was wondering if you know where I am able to access Tide Data for SC. I cannot seem to get any tide data on USGS for the coastal regions that we are interested in (maybe I am looking at the wrong place?)

**Comment by rynep** [comment]
@echao110 look at these:

https://tidesandcurrents.noaa.gov/

https://waterdata.usgs.gov/nwis/uv?referred_module=sw&search_criteria=state_cd&search_criteria=site_tp_cd&submitted_form=introduction

**Comment by echao110** [comment]
@rynep Thank you very much.
